language: node_js
sudo: false
node_js:
  - "8.9.4"
cache: yarn
branches:
  only:
    - master
    - development
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
install:
  - yarn install --ignore-engines
jobs:
  include:
    - stage: test
      script: yarn build && yarn test:build && yarn test:coverage:ci
      #- stage: release
      #if: branch = master
      #script: yarn build && yarn release
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - webiny:rw9auyqJpDRRGcVmFCektrH5