name: webiny-cms

site:
  component: "@webiny/serverless-app"
  inputs:
    description: Webiny Site
    hook: yarn build:prod
    root: ../code/site
    timeout: 10
#admin:
#  component: "@webiny/serverless-app"
#  inputs:
#    description: Webiny Admin
#    hook: yarn build:prod
#    root: ../code/admin

api:
  component: "@webiny/serverless-api-gateway"
  inputs:
    description: Serverless Site
    stage: prod
    endpoints:
      - path: /{key+}
        method: GET
        function: ${site}
      - path: /
        method: GET
        function: ${site}
