name: webiny-apps-[PROJECT_ID]

vars:
  region: ${env.AWS_REGION}
  mongodb:
    server: ${env.MONGODB_SERVER}
    name: ${env.MONGODB_NAME}

dbProxy:
  component: "@webiny/serverless-db-proxy"
  inputs:
    region: ${vars.region}
    concurrencyLimit: 15
    timeout: 30
    env:
      MONGODB_SERVER: ${vars.mongodb.server}
      MONGODB_NAME: ${vars.mongodb.name}

site:
  component: "@webiny/serverless-app"
  inputs:
    description: Webiny Site
    region: ${vars.region}
    memory: 128
    timeout: 30
    code: ./site/build
    env:
      SSR_FUNCTION: ${ssr.name}
      DB_PROXY_FUNCTION: ${dbProxy.arn}

ssr:
  component: "@webiny/serverless-function"
  inputs:
    description: Site SSR
    region: ${vars.region}
    hook: yarn build:${cli.env}
    root: ./site
    code: ./site/build-ssr
    handler: handler.handler
    memory: 2048
    timeout: 60

admin:
  component: "@webiny/serverless-app"
  inputs:
    region: ${vars.region}
    description: Webiny Admin
    hook: yarn build:${cli.env}
    root: ./admin

api:
  component: "@webiny/serverless-api-gateway"
  inputs:
    description: Serverless React Apps
    region: ${vars.region}
    binaryMediaTypes: ["*/*"]
    endpoints:
      - path: /admin/{key+}
        method: GET
        function: ${admin}
      - path: /admin
        method: GET
        function: ${admin}
      - path: /{key+}
        method: ANY
        function: ${site}
      - path: /
        method: ANY
        function: ${site}

cdn:
  component: "@webiny/serverless-aws-cloudfront"
  inputs:
    invalidateOnDeploy: true
    forwardIdViaHeaders: true
    defaults: # optional
      ttl: 300
      allowedHttpMethods: ["GET", "HEAD", "OPTIONS", "PUT", "POST", "PATCH", "DELETE"]
      forward:
        queryString: true
    origins:
      - url: ${api.url}
        allowedHttpMethods: ["HEAD", "GET"]
