name: webiny-api-[PROJECT_ID]

vars:
  region: ${env.AWS_REGION}
  debug: ${env.DEBUG}
  bucket: ${env.S3_BUCKET}
  apollo:
    server:
      introspection: ${env.GRAPHQL_INTROSPECTION}
      playground: ${env.GRAPHQL_PLAYGROUND}
  mongodb:
    server: ${env.MONGODB_SERVER}
    name: ${env.MONGODB_NAME}
  security:
    token:
      expiresIn: 2592000 # 30 days
      secret: ${env.JWT_SECRET}

gateway:
  component: "@webiny/serverless-apollo-gateway"
  inputs:
    region: ${vars.region}
    memory: 512
    timeout: 30
    debug: ${vars.debug}
    plugins:
      - factory: "@webiny/api-plugin-create-apollo-gateway"
        options:
          server: ${vars.apollo.server}
          services:
            - name: security
              url: ${security.api.graphqlUrl}
            - name: files
              url: ${files.api.graphqlUrl}
            - name: pageBuilder
              url: ${pageBuilder.api.graphqlUrl}
            - name: i18n
              url: ${i18n.api.graphqlUrl}
            - name: formBuilder
              url: ${formBuilder.api.graphqlUrl}

dbProxy:
  component: "@webiny/serverless-db-proxy"
  inputs:
    region: ${vars.region}
    concurrencyLimit: 15
    timeout: 30
    env:
      MONGODB_SERVER: ${vars.mongodb.server}
      MONGODB_NAME: ${vars.mongodb.name}

cognito:
  component: "@webiny/serverless-aws-cognito-user-pool"
  inputs:
    name: "webiny-pool-[PROJECT_ID]"
    region: ${vars.region}
    appClients:
      - name: "react-app-[PROJECT_ID]"

security:
  component: "@webiny/serverless-apollo-service"
  inputs:
    region: ${vars.region}
    memory: 512
    debug: ${vars.debug}
    plugins:
      - factory: "@webiny/api-plugin-create-apollo-handler"
        options: ${vars.apollo}
      - factory: "@webiny/api-plugin-commodo-db-proxy"
        options:
          functionArn: ${dbProxy.arn}
      - factory: "@webiny/api-security/plugins"
        options: ${vars.security}
      - factory: "@webiny/api-plugin-security-cognito"
        options:
          region: ${vars.region}
          userPoolId: ${cognito.userPool.Id}

files:
  component: "@webiny/serverless-files"
  inputs:
    region: ${vars.region}
    bucket: ${vars.bucket}
    functions:
      apolloService:
        memory: 512
        timeout: 30
        debug: ${vars.debug}
        uploadMinFileSize: 0 # 0 MB
        uploadMaxFileSize: 26214400 # 25 MB
        plugins:
          - factory: "@webiny/api-plugin-create-apollo-handler"
            options: ${vars.apollo}
          - factory: "@webiny/api-plugin-commodo-db-proxy"
            options:
              functionArn: ${dbProxy.arn}
          - factory: "@webiny/api-security/plugins/service"
            options: ${vars.security}
          - "@webiny/api-files/plugins"
          - "@webiny/api-plugin-files-resolvers-mongodb"
      downloadFile:
        memory: 512
        timeout: 30
      imageTransformer:
        memory: 1600
        timeout: 30

i18n:
  component: "@webiny/serverless-apollo-service"
  inputs:
    region: ${vars.region}
    memory: 512
    debug: ${vars.debug}
    plugins:
      - factory: "@webiny/api-plugin-create-apollo-handler"
        options: ${vars.apollo}
      - factory: "@webiny/api-plugin-commodo-db-proxy"
        options:
          functionArn: ${dbProxy.arn}
      - factory: "@webiny/api-security/plugins/service"
        options: ${vars.security}
      - "@webiny/api-i18n/plugins"

pageBuilder:
  component: "@webiny/serverless-page-builder"
  inputs:
    region: ${vars.region}
    files: ${files}
    memory: 512
    timeout: 30
    debug: ${vars.debug}
    plugins:
      - factory: "@webiny/api-plugin-create-apollo-handler"
        options: ${vars.apollo}
      - factory: "@webiny/api-plugin-commodo-db-proxy"
        options:
          functionArn: ${dbProxy.arn}
      - factory: "@webiny/api-security/plugins/service"
        options: ${vars.security}
      - "@webiny/api-page-builder/plugins"
      - "@webiny/api-page-builder/plugins/useSsrCacheTags"
      - "@webiny/api-plugin-page-builder-resolvers-mongodb"
      - "@webiny/api-google-tag-manager"
      - "@webiny/api-mailchimp"
      - "@webiny/api-cookie-policy"

formBuilder:
  component: "@webiny/serverless-form-builder"
  inputs:
    region: ${vars.region}
    files: ${files}
    i18n: ${i18n}
    memory: 512
    timeout: 30
    debug: ${vars.debug}
    plugins:
      - factory: "@webiny/api-plugin-create-apollo-handler"
        options: ${vars.apollo}
      - factory: "@webiny/api-plugin-commodo-db-proxy"
        options:
          functionArn: ${dbProxy.arn}
      - factory: "@webiny/api-security/plugins/service"
        options: ${vars.security}
      - "@webiny/api-i18n/plugins/service"
      - "@webiny/api-form-builder/plugins"
      - "@webiny/api-form-builder/plugins/useSsrCacheTags"

api:
  component: "@webiny/serverless-api-gateway"
  inputs:
    region: ${vars.region}
    description: "Main API Gateway"
    endpoints:
      - path: /graphql
        method: ANY
        function: ${gateway}

cdn:
  component: "@webiny/serverless-aws-cloudfront"
  inputs:
    origins:
      - ${files.cdnOrigin}
      - url: ${api.url}
        pathPatterns:
          "/graphql":
            ttl: 0
            forward:
              headers: ["Accept", "Accept-Language"]
            allowedHttpMethods: ["GET", "HEAD", "OPTIONS", "PUT", "POST", "PATCH", "DELETE"]
