name: Next Branch - Push

on:
  push:
    branches: [ci-cypress]

env:
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  e2e-tests:
    name: Run E2E (Cypress) tests
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Get day of month (for caching purposes)
        id: day-of-month
        run: echo "::set-output name=day::$(node --eval "console.log(new Date().getDate())")"

      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v2
        with:
          path: .webiny/cached-packages
          key: cached-packages-${{ runner.os }}-next-${{ steps.day-of-month.outputs.day }}

      - name: Install dependencies
        run: yarn --immutable

      - name: Build packages
        if: steps.cached-packages.outputs.cache-hit != 'true'
        run: yarn build

      - name: Setup - update Pulumi backend
        run: node scripts/setupPulumiBackend.js '${{ secrets.AWS_PULUMI_S3_BUCKET_NEXT_BRANCH_PREVIEW }}'

      - name: Create Pulumi.dev.yaml files
        run: |
          touch api/Pulumi.dev.yaml
          touch apps/admin/Pulumi.dev.yaml
          touch apps/website/Pulumi.dev.yaml

      - name: Upload 111preview files
        uses: actions/upload-artifact@v2
        with:
          name: preview-files
          retention-days: 1
          path: |
            api/Pulumi.yaml
            apps/admin/Pulumi.yaml
            apps/website/Pulumi.yaml

      - name: Print info
        run: yarn webiny info

      - name: Setup - setup cypress.json config file
        run: node scripts/setupCypress.js --force

      - name: Cypress - run the rest of Admin app tests
        run: yarn cypress run --spec "cypress/integration/admin/**/*.spec.js"
